name: gif_retrieval
channels:
- pytorch
- menpo
- defaults
dependencies:
- jupyter
- matplotlib
- python=3.5
- scikit-learn
- scipy
- opencv3
- cyvlfeat
- pytorch
- torchvision
- pip
- pillow
- pip:
  - visdom
- pyyaml
